Add help and -f flag

diff --git a/process_assets b/process_assets
--- a/process_assets
+++ b/process_assets
@@ -24,6 +24,37 @@ function processImage {
 	$inkscape -d 120 -e $2/res/drawable-ldpi/${file/.svg}.png $1 >& /dev/null
 }
 
+function displayHelp {
+
+		echo "-h Help"
+		echo "-f Force processing of all files"
+		echo "process_assets ./source_image_folder/ ./output_folder"
+		exit
+}
+
+while getopts ":fh" opt; do
+	case $opt in
+		f)
+			rm ./lastprocess
+			;;
+		h)
+			displayHelp
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			displayHelp
+			exit
+			;;
+	esac
+done
+
+if [ $# -ne 2 ]
+then
+	echo "Incorrect number of args." >&2
+	displayHelp
+	exit
+fi
+
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 if [ ! -e ./lastprocess ]
